[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip setuptools wheel', 'python -m pip install -r requirements.txt']

[start]
cmd = 'python -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}'
